### ISSUE TITLE
Themes viewing and Vote

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/docs#29]
Vote for themes to fix some problems:

- The sidebar text aligned problem.
- The title is too long and the text is too big, this causes to overflow sidebar.

The followings are our using or used themes.
And there are two rest official themes see https://docsify.js.org/#/themes?id=click-to-preview.

Others themes from 3rd part, see https://jhildenbiddle.github.io/docsify-themeable/#/

**Comment by Zeroto521** [comment]
## 'vue'

![image](https://user-images.githubusercontent.com/25895405/128801308-6437d475-8002-48a8-b3c8-472e1bba4eac.png)

**Comment by Zeroto521** [comment]
## 'bubble'

![image](https://user-images.githubusercontent.com/25895405/128801297-b6c8562d-6b54-45aa-95f1-21e8bba767cd.png)

**Comment by Zeroto521** [comment]
## dark

![image](https://user-images.githubusercontent.com/25895405/128802047-761f0bb8-e260-4aff-8366-a5abc0164073.png)

**Comment by jjw24** [comment]
from https://jhildenbiddle.github.io/docsify-themeable/#/themes?id=simple

I quite like 'Simple'(top picture) or 'Simple Dark':
![image](https://user-images.githubusercontent.com/26427004/128848198-9f279d18-93ca-4bb2-854a-166832a054de.png)

also the 'Bubble' theme is quite alright.

@Flow-Launcher/team

**Comment by pc223** [comment]
> from [jhildenbiddle.github.io/docsify-themeable/#/themes?id=simple](https://jhildenbiddle.github.io/docsify-themeable/#/themes?id=simple)
> 
> I quite like 'Simple'(top picture) or 'Simple Dark':
> ![image](https://user-images.githubusercontent.com/26427004/128848198-9f279d18-93ca-4bb2-854a-166832a054de.png)
> 
> also the 'Bubble' theme is quite alright.
> 
> @Flow-Launcher/team

This looks nice! I think we should avoid too many level of indentations, I think 2 levels is enough, more than than that is pretty hard to see.

**Comment by Garulf** [comment]
They all look great. But how can you not go dark mode and choose "Simple Dark"?

**Comment by jjw24** [comment]
> Was looking to adding a toggle for light and dark themes here: docsify-darklight-theme

up to you, if it's simple enough why not.

**Comment by Garulf** [comment]
Seems pretty easy, I'll take a look setting it up.

**Comment by Zeroto521** [comment]
Q: How to see the theme result?
1. fork
2. just change the following line.
https://github.com/Flow-Launcher/docs/blob/174d3924252900c8d91f1bccec0275f3daaf8cd8/index.html#L10
3. go fork project **settings**
4. go fork project **settings/pages**
5. choose a branch to build site

![image](https://user-images.githubusercontent.com/25895405/129295292-a2c52c6a-6c5c-40fd-a835-e88982d41415.png)

**Comment by Garulf** [comment]
Finally got around to adding dark-light theme toggling over at: https://github.com/Flow-Launcher/docs/pull/31
